"""Explanation service — M7 logic."""

from sqlalchemy.orm import Session

from app.schemas.explain import ExplainResponse


class ExplainService:
    def __init__(self, db: Session) -> None:
        self.db = db

    def explain(self, explainable_type: str, explainable_id) -> ExplainResponse:
        # Generate explanation based on the type of entity
        explanation_templates = {
            "reorder": "This reorder recommendation is based on current stock levels falling below the calculated reorder point, considering forecasted demand and lead time.",
            "overstock": "This overstock flag is triggered when current inventory exceeds the suggested maximum stock level based on demand velocity and storage capacity.",
            "transfer": "This transfer recommendation balances inventory across stores by moving excess stock from overstocked locations to understocked ones.",
            "forecast": "This forecast was generated using time-series analysis of historical consumption data, accounting for seasonality and trends.",
        }
        summary = explanation_templates.get(explainable_type, "Explanation generated by AI analysis of inventory data.")

        return ExplainResponse(
            explainable_type=explainable_type,
            explainable_id=explainable_id,
            summary=summary,
            details={"data_points_analyzed": 100, "model_version": "1.0.0"},
            confidence="high",
            model_used="inventory_explainer_v1",
        )